SC_float(_Progress, 1, [SCRange(0,1)], "__Progress", "__ProgressDesc")
SC_uint(_Role, 0, [SCEnum(Incoming,0,Outgoing,1,Safety Cover,2)], "__Role", "__RoleDesc")
SC_uint(_Style, 0, [SCEnum(Arcane,0,Cyber,1,Astral,2,Gaia,3,Umbra,4,Flame,5,Shatter,6,Glitch,7,Melt,8)], "__Style", "__StyleDesc")
SC_float4(_IncomingOutgoingWindow, (0.25,0.65,0.35,0.75), [], "__IncomingOutgoingWindow", "__IncomingOutgoingWindowDesc")
SC_float4(_CoverWindow, (0.1,0.3,0.7,0.9), [], "__CoverWindow", "__CoverWindowDesc")
SC_float4(_Direction, (0,1,0,0), [], "__Direction", "__DirectionDesc")
SC_float4(_Bounds, (-1,1,0,0), [], "__Bounds", "__BoundsDesc")
SC_float(_NoiseScale, 8, [SCRange(0.1,64)], "__NoiseScale", "__NoiseScaleDesc")
SC_float(_Noise, 0.35, [SCRange(0,1)], "__Noise", "__NoiseDesc")
SC_float(_EdgeWidth, 0.07, [SCRange(0.001,0.5)], "__EdgeWidth", "__EdgeWidthDesc")
SC_color(_EdgeColor, (0.15,0.8,1,1), [SCHDR], "__EdgeColor", "__EdgeColorDesc")
SC_float(_EdgeEmission, 2.5, [SCRange(0,12)], "__EdgeEmission", "__EdgeEmissionDesc")
SC_float(_Displacement, 0.12, [SCRange(0,1)], "__Displacement", "__DisplacementDesc")
SC_float(_BlockScale, 8, [SCRange(0.5,64)], "__BlockScale", "__BlockScaleDesc")
SC_Foldout(__Surface)
SC_color(_CoverColor, (0.025,0.04,0.09,1), [SCHDR], "__CoverColor", "__CoverColorDesc")
SC_color(_PatternColor, (0.2,0.75,1,1), [SCHDR], "__PatternColor", "__PatternColorDesc")
SC_float(_PatternScale, 6, [SCRange(0.1,64)], "__PatternScale", "__PatternScaleDesc")
SC_float(_PatternSpeed, 1, [SCRange(-8,8)], "__PatternSpeed", "__PatternSpeedDesc")
SC_float(_PatternEmission, 2, [SCRange(0,12)], "__PatternEmission", "__PatternEmissionDesc")
SC_FoldoutEnd
