SC_Foldout(__CrtGlitch)
SC_float(_Amount, 0, [SCRange(0,1)], "__Amount", "__AmountDesc")
SC_float(_Scanline, 0.5, [SCRange(0,1)], "__Scanline", "__ScanlineDesc")
SC_float(_ScanlinePitch, 4, [SCRange(2,32)], "__ScanlinePitch", "__ScanlinePitchDesc")
SC_float(_Mask, 0.3, [SCRange(0,1)], "__Mask", "__MaskDesc")
SC_float(_MaskPitch, 6, [SCRange(3,24)], "__MaskPitch", "__MaskPitchDesc")
SC_float(_Vignette, 0.35, [SCRange(0,1)], "__Vignette", "__VignetteDesc")
SC_float(_Aberration, 1.5, [SCRange(0,8)], "__Aberration", "__AberrationDesc")
SC_float(_Noise, 0.05, [SCRange(0,1)], "__Noise", "__NoiseDesc")
SC_float(_NoiseScale, 2, [SCRange(1,32)], "__NoiseScale", "__NoiseScaleDesc")
SC_float(_Roll, 0, [SCRange(0,1)], "__Roll", "__RollDesc")
SC_float(_RollSpeed, 0.15, [SCRange(0,2)], "__RollSpeed", "")
SC_float(_Glitch, 0, [SCRange(0,1)], "__Glitch", "__GlitchDesc")
SC_float(_GlitchScale, 12, [SCRange(1,64)], "__GlitchScale", "__GlitchScaleDesc")
SC_float(_GlitchShift, 6, [SCRange(0,32)], "__GlitchShift", "__GlitchShiftDesc")
SC_float(_GlitchColor, 0.5, [SCRange(0,1)], "__GlitchColor", "__GlitchColorDesc")
SC_float(_Tearing, 0, [SCRange(0,0.2)], "__Tearing", "__TearingDesc")
SC_float(_TearScale, 0.05, [SCRange(0.005,0.5)], "__TearScale", "__TearScaleDesc")
SC_FoldoutEnd
