SC_float(_Progress, 1, [SCRange(0,1)], "__Progress", "__ProgressDesc")
SC_uint(_Mode, 0, [SCEnum(Upward Dissolve,0,Glitch Spawn,1,Liquid to Solid,2)], "__Mode", "__ModeDesc")
SC_float4(_Direction, (0,1,0,0), [], "__Direction", "__DirectionDesc")
SC_float4(_Bounds, (-1,1,0,0), [], "__Bounds", "__BoundsDesc")
SC_float(_NoiseScale, 8, [SCRange(0.1,64)], "__NoiseScale", "__NoiseScaleDesc")
SC_float(_Noise, 0.3, [SCRange(0,1)], "__Noise", "__NoiseDesc")
SC_float(_EdgeWidth, 0.06, [SCRange(0.001,0.5)], "__EdgeWidth", "__EdgeWidthDesc")
SC_color(_EdgeColor, (0.15,0.8,1,1), [SCHDR], "__EdgeColor", "__EdgeColorDesc")
SC_float(_EdgeEmission, 2, [SCRange(0,8)], "__EdgeEmission", "__EdgeEmissionDesc")
SC_float(_Displacement, 0.2, [SCRange(0,1)], "__Displacement", "__DisplacementDesc")
SC_float(_BlockScale, 8, [SCRange(0.5,64)], "__BlockScale", "__BlockScaleDesc")
SC_Foldout(__Liquid)
SC_float(_LiquidAmplitude, 0.06, [SCRange(0,0.5)], "__LiquidAmplitude", "__LiquidAmplitudeDesc")
SC_float(_LiquidFrequency, 5, [SCRange(0.1,32)], "__LiquidFrequency", "__LiquidFrequencyDesc")
SC_float(_LiquidSpeed, 1, [SCRange(-8,8)], "__LiquidSpeed", "__LiquidSpeedDesc")
SC_color(_LiquidTint, (0.25,0.55,1,0.35), [SCHDR], "__LiquidTint", "__LiquidTintDesc")
SC_FoldoutEnd
