SC_Foldout(__SurfaceOverlay)
SC_float(_Amount, 0, [SCRange(0,1)], "__Amount", "__AmountDesc")
SC_Texture2D(_Texture, "white", [], "__Texture", "__TextureDesc")
SC_ScaleOffset(_Texture)
SC_color(_Color, (0.62,0.58,0.5,1), [], "__Color", "")
SC_uint(_MaskChannel, 4, [SCEnum(R,0,G,1,B,2,A,3,None,4)], "__MaskChannel", "__MaskChannelDesc")
SC_float(_UpBias, 0.8, [SCRange(0,1)], "__UpBias", "__UpBiasDesc")
SC_float(_Border, 0.6, [SCRange(0,1)], "__Border", "__BorderDesc")
SC_float(_Blur, 0.15, [SCRange(0,1)], "__Blur", "")
SC_float(_Darken, 0, [SCRange(0,1)], "__Darken", "__DarkenDesc")
SC_float(_Flatten, 0, [SCRange(0,1)], "__Flatten", "__FlattenDesc")
SC_float(_Streak, 0, [SCRange(0,1)], "__Streak", "__StreakDesc")
SC_float(_StreakScale, 24, [SCRange(1,128)], "__StreakScale", "")
SC_float(_StreakSpeed, 0.6, [SCRange(0,4)], "__StreakSpeed", "")
SC_FoldoutEnd
