SC_Foldout(__SurfaceOverlay)
SC_float(_Amount, 0, [SCRange(0,1)], "__Amount", "__AmountDesc")
SC_Texture2D(_Texture, "white", [], "__Texture", "__TextureDesc")
SC_ScaleOffset(_Texture)
SC_color(_Color, (0.62,0.58,0.5,1), [], "__Color", "")
SC_uint(_MaskChannel, 4, [SCEnum(R,0,G,1,B,2,A,3,None,4)], "__MaskChannel", "__MaskChannelDesc")
SC_float(_UpBias, 0.8, [SCRange(0,1)], "__UpBias", "__UpBiasDesc")
SC_float(_Border, 0.6, [SCRange(0,1)], "__Border", "__BorderDesc")
SC_float(_Blur, 0.15, [SCRange(0,1)], "__Blur", "")
SC_float(_Darken, 0, [SCRange(0,1)], "__Darken", "__DarkenDesc")
SC_float(_Flatten, 0, [SCRange(0,1)], "__Flatten", "__FlattenDesc")
SC_float(_Thickness, 0, [SCRange(0,0.1)], "__Thickness", "__ThicknessDesc")
SC_uint(_VertexMaskChannel, 4, [SCEnum(R,0,G,1,B,2,A,3,None,4)], "__VertexMaskChannel", "__VertexMaskChannelDesc")
SC_float(_Droplet, 0, [SCRange(0,1)], "__Droplet", "__DropletDesc")
SC_float(_DropletScale, 40, [SCRange(1,200)], "__DropletScale", "")
SC_float(_DropletSize, 0.28, [SCRange(0.02,0.5)], "__DropletSize", "")
SC_float(_DropletVariance, 0.6, [SCRange(0,1)], "__DropletVariance", "__DropletVarianceDesc")
SC_float(_DropletBump, 1, [SCRange(0,4)], "__DropletBump", "__DropletBumpDesc")
SC_float(_Mobility, 0, [SCRange(0,1)], "__Mobility", "__MobilityDesc")
SC_float(_Streak, 0, [SCRange(0,1)], "__Streak", "__StreakDesc")
SC_float(_StreakSpeed, 0.6, [SCRange(0,4)], "__StreakSpeed", "")
SC_FoldoutEnd
