SC_float(_Amount, 0, [SCRange(0,1)], "__Amount", "__AmountDesc")
SC_Texture2D(_Texture, "white", [], "__Texture", "__TextureDesc")
SC_ScaleOffset(_Texture)
SC_color(_Tint, (1,1,1,1), [SCHDR], "__Tint", "__TintDesc")
SC_uint(_Mapping, 0, [SCEnum(UV Space,0,Projection,1)], "__Mapping", "__MappingDesc")
SC_uint(_UVChannel, 0, [SCEnum(UV0,0,UV1,1,UV2,2,UV3,3)], "__UVChannel", "__UVChannelDesc")
SC_uint(_BlendMode, 0, [SCEnum(Alpha,0,Multiply,1,Add,2)], "__BlendMode", "__BlendModeDesc")
SC_uint(_MaskChannel, 4, [SCEnum(R,0,G,1,B,2,A,3,None,4)], "__MaskChannel", "__MaskChannelDesc")
SC_Foldout(__Projection)
SC_float4(_ProjectorCenter, (0,0,0,0), [], "__ProjectorCenter", "__ProjectorCenterDesc")
SC_float4(_ProjectorRotation, (0,0,0,0), [], "__ProjectorRotation", "__ProjectorRotationDesc")
SC_float4(_ProjectorSize, (1,1,0.2,0), [], "__ProjectorSize", "__ProjectorSizeDesc")
SC_float(_AngleFade, 0.2, [SCRange(-1,1)], "__AngleFade", "__AngleFadeDesc")
SC_float(_EdgeSoftness, 0.03, [SCRange(0,0.5)], "__EdgeSoftness", "__EdgeSoftnessDesc")
SC_FoldoutEnd
