"""各 shader と module の Core HLSL を GLSL のテストシーンに組み立てる。

コアの HLSL は改変せずそのまま連結する。テスト対象と出荷物を同じコードに
保つのがこのハーネスの目的なので、ここで書き換えを入れてはいけない。
"""

from __future__ import annotations

import re
from typing import Dict, List, Optional, Sequence, Tuple

from .paths import CORE_HLSL, MODULES_DIR, PRELUDE_GLSL, SCENE_FRAG, SHADERS_DIR

_STRUCT_RE = r"struct\s+{name}\s*\{{(.*?)\}}\s*;"
_FIELD_RE = re.compile(r"^\s*(half|half2|half3|half4|float|float2|float3|float4)\s+(\w+)\s*;")

_SCALAR_TYPES = {"half", "float"}
_VECTOR_SIZES = {"half2": 2, "half3": 3, "half4": 4, "float2": 2, "float3": 3, "float4": 4}


def read_core() -> str:
    return CORE_HLSL.read_text(encoding="utf-8")


def shader_cores() -> List[Tuple[str, str]]:
    """Illust2D 以外の shader が持つ、Unity 非依存の数式ファイル。"""
    if not SHADERS_DIR.is_dir():
        return []
    return [
        (path.relative_to(SHADERS_DIR).as_posix(), path.read_text(encoding="utf-8"))
        for path in sorted(SHADERS_DIR.rglob("*Core.hlsl"))
        if path != CORE_HLSL
    ]


def module_cores() -> List[Tuple[str, str]]:
    """モジュールの数式ファイル。シェーダー本体の Core と同じ制約で書かれている。"""
    if not MODULES_DIR.is_dir():
        return []
    return [
        (path.name, path.read_text(encoding="utf-8"))
        for path in sorted(MODULES_DIR.rglob("*Core.hlsl"))
    ]


def parse_struct_fields(source: str, name: str) -> List[Tuple[str, str]]:
    """`struct <name> { ... };` のフィールドを (型, 名前) で返す。"""
    match = re.search(_STRUCT_RE.format(name=re.escape(name)), source, re.DOTALL)
    if match is None:
        raise ValueError(f"struct {name} が見つかりません")

    fields: List[Tuple[str, str]] = []
    for line in match.group(1).splitlines():
        line = line.split("//", 1)[0]
        field = _FIELD_RE.match(line)
        if field:
            fields.append((field.group(1), field.group(2)))
    return fields


def _literal(value: float) -> str:
    """必ず小数点を含む GLSL の float リテラルにする。"""
    text = repr(float(value))
    if "e" in text or "E" in text:
        text = f"{float(value):.10f}"
    if "." not in text:
        text += ".0"
    return text


def _emit_value(field_type: str, value) -> str:
    if field_type in _SCALAR_TYPES:
        if isinstance(value, (list, tuple)):
            raise TypeError(f"スカラー型 {field_type} にベクターが渡されました: {value}")
        return _literal(value)

    size = _VECTOR_SIZES[field_type]
    if not isinstance(value, (list, tuple)) or len(value) != size:
        raise TypeError(f"{field_type} には長さ {size} の列が必要です: {value}")
    joined = ", ".join(_literal(v) for v in value)
    return f"vec{size}({joined})"


def emit_style(
    fields: Sequence[Tuple[str, str]],
    params: Dict[str, object],
    *,
    struct: str = "SBSStyle",
    function: str = "sceneStyle",
) -> str:
    """構造体を組み立てて返す GLSL 関数を生成する。"""
    missing = [name for _, name in fields if name not in params]
    if missing:
        raise KeyError(f"スタイルの指定が足りません: {', '.join(missing)}")
    unknown = [name for name in params if name not in {n for _, n in fields}]
    if unknown:
        raise KeyError(f"{struct} に存在しないフィールドです: {', '.join(sorted(unknown))}")

    lines = [f"{struct} {function}()", "{", f"    {struct} st;"]
    for field_type, name in fields:
        lines.append(f"    st.{name} = {_emit_value(field_type, params[name])};")
    lines.append("    return st;")
    lines.append("}")
    return "\n".join(lines)


def build_scene_source(
    *,
    style: Dict[str, object],
    mode: int,
    resolution: Tuple[int, int],
    light_dir: Sequence[float],
    light_color: Sequence[float],
    ambient: Sequence[float],
    outline: Dict[str, object],
    module_styles: Optional[Dict[str, Dict[str, object]]] = None,
    gamma: float = 2.2,
) -> str:
    core = read_core()
    fields = parse_struct_fields(core, "SBSStyle")

    shaders = shader_cores()
    shader_source = "\n".join(f"// ---- {name} ----\n{body}" for name, body in shaders)
    modules = module_cores()
    module_source = "\n".join(f"// ---- {name} ----\n{body}" for name, body in modules)

    # モジュールの数式もゴールデンで守るため、スタイルを本体と同じ仕組みで注入する。
    # SBSXxxStyle という構造体を見つけたら sceneXxxStyle() を生成する。
    module_styles = module_styles or {}
    style_blocks: List[str] = []
    for name, body in modules:
        for struct in sorted(set(re.findall(r"struct\s+(SBS\w+Style)\s*\{", body))):
            if struct not in module_styles:
                raise KeyError(f"{name} の {struct} に対応するスタイルが渡されていません")
            style_blocks.append(
                emit_style(
                    parse_struct_fields(body, struct),
                    module_styles[struct],
                    struct=struct,
                    function="scene" + struct[3:],
                )
            )

    header = "\n".join(
        [
            "// ---- generated by tests/harness/glsl.py ----",
            f"const vec2 SCENE_RESOLUTION = vec2({resolution[0]}.0, {resolution[1]}.0);",
            f"const int SCENE_MODE = {int(mode)};",
            f"const vec3 SCENE_LIGHT_DIR = {_emit_value('half3', list(light_dir))};",
            f"const vec3 SCENE_LIGHT_COLOR = {_emit_value('half3', list(light_color))};",
            f"const vec3 SCENE_AMBIENT = {_emit_value('half3', list(ambient))};",
            f"const float SCENE_GAMMA = {_literal(gamma)};",
            f"const vec3 SCENE_OUTLINE_COLOR = {_emit_value('half3', list(outline['color']))};",
            f"const float SCENE_OUTLINE_HUE = {_literal(outline['hueShift'])};",
            f"const float SCENE_OUTLINE_SAT = {_literal(outline['saturation'])};",
            f"const float SCENE_OUTLINE_VALUE = {_literal(outline['value'])};",
            "",
            emit_style(fields, style),
            "",
            "\n\n".join(style_blocks),
        ]
    )

    return "\n".join(
        [
            PRELUDE_GLSL.read_text(encoding="utf-8"),
            "// ---- Packages/io.github.sabas0ba.sabashader/Shaders/Illust2D/Illust2DCore.hlsl ----",
            core,
            shader_source,
            module_source,
            header,
            "// ---- tests/harness/scene.frag ----",
            SCENE_FRAG.read_text(encoding="utf-8"),
        ]
    )


VERTEX_SHADER = """#version 330 core
void main()
{
    vec2 v = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2));
    gl_Position = vec4(v * 2.0 - 1.0, 0.0, 1.0);
}
"""
