SC_float(_Amount, 0, [SCRange(0,1)], "__Amount", "__AmountDesc")
SC_uint(_Preset, 0, [SCEnum(Universe,0,Starfield,1,Cyber,2,Mud,3)], "__Preset", "__PresetDesc")
SC_uint(_Side, 1, [SCEnum(Front,0,Back,1,Both,2)], "__Side", "__SideDesc")
SC_uint(_Region, 0, [SCEnum(Full Surface,0,Rift,1)], "__Region", "__RegionDesc")
SC_uint(_MaskChannel, 4, [SCEnum(R,0,G,1,B,2,A,3,None,4)], "__MaskChannel", "__MaskChannelDesc")
SC_color(_ColorA, (0.015,0.025,0.09,1), [SCHDR], "__ColorA", "__ColorADesc")
SC_color(_ColorB, (0.35,0.08,0.55,1), [SCHDR], "__ColorB", "__ColorBDesc")
SC_float(_Emission, 2, [SCRange(0,8)], "__Emission", "__EmissionDesc")
SC_float(_Scale, 5, [SCRange(0.1,64)], "__Scale", "__ScaleDesc")
SC_float(_Depth, 2, [SCRange(0,16)], "__Depth", "__DepthDesc")
SC_float(_Parallax, 1, [SCRange(0,2)], "__Parallax", "__ParallaxDesc")
SC_float(_StarDensity, 0.28, [SCRange(0,1)], "__StarDensity", "__StarDensityDesc")
SC_float(_StarSize, 0.18, [SCRange(0.02,0.5)], "__StarSize", "__StarSizeDesc")
SC_float(_Nebula, 0.7, [SCRange(0,2)], "__Nebula", "__NebulaDesc")
SC_float(_NebulaScale, 0.55, [SCRange(0.05,4)], "__NebulaScale", "__NebulaScaleDesc")
SC_float(_TimeScale, 0.05, [SCRange(-2,2)], "__TimeScale", "__TimeScaleDesc")
SC_Foldout(__Rift)
SC_float4(_RiftCenter, (0.5,0.5,0,0), [], "__RiftCenter", "__RiftCenterDesc")
SC_float4(_RiftSize, (0.8,0.8,0,0), [], "__RiftSize", "__RiftSizeDesc")
SC_float(_RiftNoise, 0.22, [SCRange(0,0.8)], "__RiftNoise", "__RiftNoiseDesc")
SC_float(_EdgeWidth, 0.08, [SCRange(0.001,0.5)], "__EdgeWidth", "__EdgeWidthDesc")
SC_color(_EdgeColor, (0.15,0.8,1,1), [SCHDR], "__EdgeColor", "__EdgeColorDesc")
SC_FoldoutEnd
