SC_Texture2D(_BaseTexture, "white", [SCMainTexture], "__Texture", "")
SC_ScaleOffset(_BaseTexture)
SC_SamplerState(sampler_BaseTexture)
SC_color(_BaseColor, (1,1,1,1), [], "__Color", "")
SC_Texture2DArray(_SharedGradients, "white", [SCGradients], "__SharedGradients", "")
SC_Texture2D(_NormalMap, "bump", [], "__NormalMap", "")
SC_float(_NormalScale, 1, [SCCache][SCRange(-10,10)], "__NormalScale", "")
SC_float(_Roughness, 0.18, [SCRange(0.002,1)], "__Roughness", "")
SC_uint(_Cull, 2, [SCEnum(Off,0,Front,1,Back,2)], "__Cull", "__CullDesc")

SC_Foldout(__Acrylic)
SC_float(_DepthScale, 1, [SCRange(0.02,1)], "__DepthScale", "__DepthScaleDesc")
SC_float(_Flatness, 0.85, [SCRange(0,1)], "__Flatness", "__FlatnessDesc")
SC_float(_ShadeThreshold, 0.45, [SCRange(0,1)], "__ShadeThreshold", "__ShadeThresholdDesc")
SC_uint(_SurfaceShadowEnabled, 1, [SCToggle], "__SurfaceShadowEnabled", "__SurfaceShadowEnabledDesc")
SC_float(_PaperGrain, 0.08, [SCRange(0,1)], "__PaperGrain", "__PaperGrainDesc")
SC_float(_PaperGrainScale, 180, [SCRange(1,1000)], "__PaperGrainScale", "")
SC_float(_Opacity, 0.65, [SCRange(0,1)], "__Opacity", "__OpacityDesc")
SC_float(_Thickness, 0.7, [SCRange(0,2)], "__Thickness", "__ThicknessDesc")
SC_float(_RefractionStrength, 0.08, [SCRange(0,0.25)], "__RefractionStrength", "__RefractionStrengthDesc")
SC_float(_RefractionScale, 1, [SCRange(0,4)], "__RefractionScale", "__RefractionScaleDesc")
SC_float(_InternalLight, 0.75, [SCRange(0,2)], "__InternalLight", "__InternalLightDesc")
SC_color(_TransmissionColor, (0.35,0.8,1,1), [], "__TransmissionColor", "")
SC_float(_TransmissionStrength, 0.22, [SCRange(0,2)], "__TransmissionStrength", "")
SC_color(_EdgeColor, (0.25,0.85,1,1), [SCHDR], "__EdgeColor", "")
SC_float(_EdgeWidth, 0.01, [SCRange(0.001,0.05)], "__EdgeWidth", "__EdgeWidthDesc")
SC_float(_RimWidth, 0, [SCRange(0,0.15)], "__RimWidth", "__RimWidthDesc")
SC_float(_EdgePower, 3, [SCRange(0.1,16)], "__EdgePower", "")
SC_float(_EdgeIntensity, 0.8, [SCRange(0,4)], "__EdgeIntensity", "")
SC_float(_WhiteBorderWidth, 0.06, [SCRange(0,0.2)], "__WhiteBorderWidth", "__WhiteBorderWidthDesc")
SC_color(_WhiteBorderColor, (1,1,1,1), [], "__WhiteBorderColor", "")
SC_FoldoutEnd

SC_Foldout(__Specular)
SC_color(_SpecularColor, (0.8,0.95,1,1), [SCHDR], "__SpecularColor", "")
SC_float(_SpecularIntensity, 1.2, [SCRange(0,4)], "__SpecularIntensity", "")
SC_float(_SpecularPower, 96, [SCRange(1,256)], "__SpecularPower", "")
SC_FoldoutEnd

SC_Foldout(__LightSettings)
SC_uint(_CastShadowEnabled, 1, [SCToggle], "__CastShadowEnabled", "__CastShadowEnabledDesc")
SC_float(_SHLightWeight, 1, [SCRange(0,2)], "__SHLightWeight", "")
SC_float(_SHLightDirectionWeight, 0.6, [SCRange(0,2)], "__SHLightDirectionWeight", "")
SC_FoldoutEnd
